services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: go_menus_dev
    container_name: go_menus_dev_container
    restart: unless-stopped
    tty: true
    environment:
      - APP_ENV=development
      - APP_PORT=8001
      - DATABASE_PORT=5432
      - DATABASE_HOST=db
      - DATABASE_USER=admindev
      - DATABASE_PASSWORD=4dm1n123
      - DATABASE_NAME=db_gomenus
      - DATABASE_MAX_OPEN_CONNECTION=10
      - DATABASE_MAX_IDLE_CONNECTION=20
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - go_menus_network
    ports:
      - "8001:8001"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_menu_dev
    restart: always
    environment:
      - POSTGRES_USER=admindev
      - POSTGRES_PASSWORD=4dm1n123
      - POSTGRES_DB=db_gomenus
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - go_menus_network

  migrate:
    image: migrate/migrate:latest
    container_name: migrate_gomenus_dev
    networks:
      - go_menus_network
    volumes:
      - ./db/migrations:/migrations
    depends_on:
      - db
    entrypoint: [
        "sh",
        "-c",
        "until nc -z db 5432; do echo 'Waiting for Postgres...'; sleep 2; done; \
        echo 'Postgres is ready!'; \
        migrate -path=/migrations -database postgres://admindev:4dm1n123@db:5432/db_gomenus?sslmode=disable up",
      ]

  pgadmin:
    image: dpage/pgadmin4:9.10.0
    container_name: pgadmin_menu_dev
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=okeokeoke
    ports:
      - "5055:80"
    depends_on:
      - db
    networks:
      - go_menus_network

volumes:
  postgres_data:

networks:
  go_menus_network:
    driver: bridge
